### PR TITLE
Improve encoder precision and reduce accidental clicks and scrolls.

### PR DESCRIPTION
**Pull request by dbuezas**
I recently got an UM2 as a gift and realised that the rotary encoder feels irresponsive and I often end up clicking the wrong thing.

## This MR improves control by

* Adding hysteresis. Each menu item is always a full "tic" away. Before, right after one scroll, you were half a tic away from the previous one, and 8 half tics from the next one. Each physical "tic" of the encoder now perfectly corresponds to a scroll.
* Adding a subtle sound feedback each time any menu is scrolled.
* Ignoring button presses that happen too close to a scroll. So no more accidentally selecting the wrong menu item.
* Ignoring scrolls to close to the last button press. 
* With all of this making the encoder so precise, the the amount of encoder tics per menu action can be reduced from 8 half ticks to 1 full tic in the main menu, and from 4 halfs to 1 full in submenues. So I changed that too.

Given how low the activity in this repo has been lately, I don't expect this MR to be merged. Instead, I hope other late comers (like myself) may enjoy these modifications.

And I must say: thanks for making this firmware, it is so much better than stock!

### CODE REVIEW

**Comment by gr5** [comment]
> Given how low the activity in this repo has been lately, I don't expect this MR to be merged

You'd be surprised!

**Comment by dbuezas** [comment]
> You'd be surprised!

Indeed, I *would* be surprised

**Comment by TinkerGnome** [comment]
I am surprised that my GitHub account still works... :smile:

low activity == low chance of conflicts, so.... that worked out well!

My UM2 is retired, that means i can't test it myself anymore.
It sounds like a very useful change and gr5 likes it - so that worked out well too!
Thank you!

**Comment by dbuezas** [comment]
Alright, I AM surprised :)
Now I wonder if marlin 2 is worth a try in the ultimaker 2

**Comment by TinkerGnome** [comment]
> Now I wonder if marlin 2 is worth a try in the ultimaker 2

Personally i would rather ditch the old electronics and replace it with a Duet3D (or whatever counts as "state of the art" nowadays). Quiet stepper drivers are a huge QOL improvement.
I think there are successful examples documented in the UM community forum.
I don't see any ground breaking features in Marlin2 an UM2 could really benefit from.
As always: IMHO and YMMV :smiley:

**Comment by dbuezas** [comment]
Thank you for your advice! Much appreciated.

For now I added the dreaded stepper dampers and replaced all fans with magnetic levitation motors (and made myself a small circuit to drive them via pwm which they don't tolerate).
I'll convert it to 1.75mm filament next, get a better extruder, and all the other tweaks us newbies seem to want to do 😅, and then maybe replace the board with a modern one with better stepper drivers.
Tbh, I enjoy the simplicity and compilation speed of 8bit micros, so I may stay 2010s for a while

**Comment by dbuezas** [comment]
I did end up replacing the board as you suggested. Thanks for the recommendation. 
I picked a latest generation one, ans SKR 3 which is a powerhouse. Was welcomed with screen and thermistor incompatibilities, but luckily solved with some soldering and a PR.
Marlin 2 also does something similar like this PR, but an encoder count threshold is used instead of a secondary substep counter as I did.
Anyway, thanks for the recommendation, the machine is definitely better now

**Pull request merged**
